# Generated by Django 3.2.4 on 2021-06-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de roupa')),
                ('cloth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tecido')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='tamanho')),
                ('cor', models.CharField(blank=True, max_length=20, null=True, verbose_name='color')),
            ],
            options={
                'verbose_name_plural': 'Clothes',
            },
        ),
    ]
